VOTER_DTYPES = {'ncid': object, 'voter_reg_num': object,
                'first_name': object, 'middle_name': object,
                'last_name': object,
                'status_cd': object, 'reason_cd': object,
                'absent_ind': object,
                'res_street_address': object,
                'res_city_desc': object, 'state_cd': object,
                'zip_code': object,
                'mail_addr1': object, 'mail_addr2': object,
                'mail_addr3': object, 'mail_addr4': object,
                'mail_city': object, 'mail_state': object,
                'mail_zipcode': object,
                'full_phone_number': object, 'drivers_lic': object,
                'race_code': object, 'ethnic_code': object,
                'party_cd': object,
                'gender_code': object, 'birth_year': int,  # 'birth_age': int,
                'birth_state': object,
                'registr_dt': str,
                'county_id': int, 'precinct_abbrv': object,
                'cong_dist_abbrv': object, 'nc_senate_abbrv': object,
                'nc_house_abbrv': object}

VOTER_SUBSET = ['ncid', 'voter_reg_num',
                'first_name', 'middle_name', 'last_name',
                'status_cd', 'reason_cd',
                'absent_ind',
                'res_street_address', 'res_city_desc', 'state_cd', 'zip_code',
                'mail_addr1', 'mail_addr2', 'mail_addr3', 'mail_addr4',
                'mail_city', 'mail_state', 'mail_zipcode',
                'full_phone_number', 'drivers_lic',
                'race_code', 'ethnic_code', 'party_cd',
                'gender_code', 'birth_year',  # 'birth_age',
                               'birth_state',
                'registr_dt',
                'county_id', 'precinct_abbrv',
                'cong_dist_abbrv', 'nc_senate_abbrv', 'nc_house_abbrv']
