raw_col_dtypes = {'county_id': object,
'county_desc': object,
'voter_reg_num': object,
'status_cd': object,
'voter_status_desc': object,
'reason_cd': object,
'voter_status_reason_desc': object,
'absent_ind': object,
'name_prefx_cd': object,
'last_name': object,
'first_name': object,
'middle_name': object,
'name_suffix_lbl': object,
'res_street_address': object,
'res_city_desc': object,
'state_cd': object,
'zip_code': object,
'mail_addr1': object,
'mail_addr2': object,
'mail_addr3': object,
'mail_addr4': object,
'mail_city': object,
'mail_state': object,
'mail_zipcode': object,
'full_phone_number': object,
'race_code': object,
'ethnic_code': object,
'party_cd': object,
'gender_code': object,
'birth_age': object,
'birth_state': object,
'drivers_lic': object,
'registr_dt': object,
'precinct_abbrv': object,
'precinct_desc': object,
'municipality_abbrv': object,
'municipality_desc': object,
'ward_abbrv': object,
'ward_desc': object,
'cong_dist_abbrv': object,
'super_court_abbrv': object,
'judic_dist_abbrv': object,
'nc_senate_abbrv': object,
'nc_house_abbrv': object,
'county_commiss_abbrv': object,
'county_commiss_desc': object,
'township_abbrv': object,
'township_desc': object,
'school_dist_abbrv': object,
'school_dist_desc': object,
'fire_dist_abbrv': object,
'fire_dist_desc': object,
'water_dist_abbrv': object,
'water_dist_desc': object,
'sewer_dist_abbrv': object,
'sewer_dist_desc': object,
'sanit_dist_abbrv': object,
'sanit_dist_desc': object,
'rescue_dist_abbrv': object,
'rescue_dist_desc': object,
'munic_dist_abbrv': object,
'munic_dist_desc': object,
'dist_1_abbrv': object,
'dist_1_desc': object,
'dist_2_abbrv': object,
'dist_2_desc': object,
'confidential_ind': object,
'birth_year': object,
'ncid': object,
'vtd_abbrv': object,
'vtd_desc': object}

voterfile_select_cols = ['county_id', 'voter_reg_num', 'status_cd', 'absent_ind', 
                         'first_name', 'middle_name', 'last_name',
                         'res_street_address', 'res_city_desc', 'state_cd', 'zip_code',
                         'mail_addr1', 'mail_addr2', 'mail_addr3', 'mail_addr4',
                         'mail_city', 'mail_state', 'mail_zipcode',
                         'full_phone_number',
                         'race_code', 'ethnic_code', 'party_cd', 'gender_code', 'birth_year', 'birth_age', 'birth_state',
                         'registr_dt', 'precinct_abbrv', 'precinct_desc', 'municipality_abbrv', 'municipality_desc',
                         'ward_abbrv', 'ward_desc',
                         'school_dist_abbrv', 'school_dist_desc'
                         'cong_dist_abbrv', 'super_court_abbrv', 'nc_senate_abbrv']